### PR TITLE
Using mbstring (improve performance on localhost)

### PR DESCRIPTION
**Pull request by ramtin2025**
When there is a large amount of CSS content, the preg_replace function freezes apache on localhost (Xampp or Wamp)

### CODE REVIEW

**Comment by ramtin2025** [comment]
@Krinkle 
Please response to my PR

**Comment by Krinkle** [comment]
@ramtin2025 Thanks for the pull request! And sorry about CSSJanus freezing your server...

This library is used as part of [ResourceLoader](https://www.mediawiki.org/wiki/ResourceLoader) in production at Wikimedia Foundation where it regularly processes pretty large bodies of CSS on the cluster serving Wikipedia.

Contributions (and especially performance improvements) are very welcome. CSSJanus is used in the critical path for rendering of stylesheets, and thus performance matters a lot there.

Do you have any benchmarks or numbers from your experience? I'd also like to verify these findings and run them against some of our own data sets. (I should probably add a proper benchmark to this repo.)

While ResourceLoader and CSSJanus are the critical path, it is heavily cached. There are other, more "hot" code paths in the MediaWiki software that I think could also benefit from this. Given most of those other code paths are older and more mature than CSSJanus, I'm somewhat surprised that there are 0 matches for  `mb_eregi_replace` in our projects. (Might be a reason for that?)

PS: Thanks for updating the commit to match the coding style, much appreciated!

**Comment by ramtin2025** [comment]
@Krinkle 

Thanks for your response. To understand what is the issue, please check the following link which has similar issue to us : 

https://stackoverflow.com/questions/7620910/regexp-in-preg-match-function-returning-browser-error

This problem is only shown on Windows and it will be reduced the performance issue by changing mpm_winnt_module to handle bigger file size but it's not the proper solution to solve this issue completely ( this solution still doesn't work for our project size "500K").

The ``mb_eregi_replace`` worked in our project well as I sent in my PR.

We are going to use "cssjanus" in an opensource project and we would like to use your GitHub rep directly.

Regards

**Comment by Danoosh** [comment]
Thank you @Krinkle !
Please use patterns without any "/" and "i" in mb_eregi_replace method. There isn't any difference between preg_replace and mb_eregi_replace in result.

$css = mb_eregi_replace(trim(rtrim(self::$patterns['right'], 'i'), '/'), 'left', $css);

**Comment by mehrshadz** [comment]
Dear @Krinkle,
 
Did you checked @ramtin2025 and @Danoosh comments?
We're waiting for your response

Thanks

**Comment by ramtin2025** [comment]
@Krinkle 
We're still waiting for your response.

Thanks

**Comment by Krinkle** [comment]
@ramtin2025 As mentioned, I'm very interested in improving the performance of CSSJanus, and I can make some time to review and verify your changes and findings. However I'd prefer if you could provide a benchmark that shows how this improves performance?

After searching on the web, I found no indication that `mb_ereg_replace` is known to perform better than `preg_replace` (either in speed, or in memory usage).

I created a basic benchmark of my own at https://gist.github.com/Krinkle/bd4fc4f361794045ab4fce419b2c9004 and found that:

On a MacBook Pro running PHP 5.6, `mb_regex` is on average about 0.1x (10-20%) faster, but no difference in memory usage.

Trying in other PHP versions at <https://3v4l.org/JB78W>, however, I found that:

* PHP 7.2.x: `preg_reg` 10x faster.
* PHP 7.1.x: `preg_reg` 5-10x faster.
* PHP 7.0.x: `preg_reg` 6-8x faster.
* HHVM 3.21: `preg_reg` 6x faster.
* HHVM 3.20: `preg_reg` 6-7x faster.
* HHVM 3.18: `preg_reg` 6-7x faster.
* PHP 5.6: `mb_regex` 0.3x faster.

**Comment by mehrshadz** [comment]
Hello @Krinkle,

You're right. It's not better than preg_replace you've used, but, the mb_ereg_replace does work well on Windows OS and windows-related virtual servers such as WAMP or XAMPP where the preg_replace freeze these servers for big files. To test it, you can convert a 500kb CSS file on Windows OS by WAMP/XAMPP using css-Janus.

cheers,

**Comment by ramtin2025** [comment]
Hi @Krinkle 
We want to use "php-CssJanus" in [PrestaShop](https://github.com/PrestaShop/PrestaShop) and as @mehrshadz said, it does not work well on Windows OS and causes Apache to freeze. That's why we have not been able to place "php-CssJanus"in the released versions of PrestaShop yet.

**Comment by Krinkle** [comment]
Thanks. I'll try to reproduce it and use this patch to find an adequate solution that also addresses performance concerns on other platforms and PHP versions.

However, I don't have access to a Windows development environment at the moment so this may take some time unfortunately.

Note to self:
* (2006) <https://bugs.php.net/bug.php?id=38728>
* (2010) <http://killtheradio.net/tricks-hacks/phps-preg-functions-dont-release-memory/>
* (2012) <https://stackoverflow.com/a/33329959/319266>

**Comment by Danoosh** [comment]
Hello @Krinkle ,

preg_replace uses PCRE for modifying patterns: 
https://secure.php.net/manual/en/reference.pcre.pattern.modifiers.php
https://secure.php.net/manual/en/function.preg-replace.php

It seems regex-pcre doesn't support Windows as well:
https://stackoverflow.com/questions/21979694/regex-pcre-on-windows

May be useful ;)

**Comment by eternoendless** [comment]
Hi @Krinkle,

This PR actually addresses a silent failure on some CSS files such as this one: https://github.com/PrestaShop/PrestaShop/blob/452ca0ff1d314b7c2e3f3824fb0a32cfea8a7d8b/admin-dev/themes/new-theme/public/theme.css

You can test it yourself on v1.2.0 using this simple PHP script:
```php
<?php

include 'src/CSSJanus.php';

$content = file_get_contents('https://raw.githubusercontent.com/PrestaShop/PrestaShop/452ca0ff1d314b7c2e3f3824fb0a32cfea8a7d8b/admin-dev/themes/new-theme/public/theme.css');
var_dump('read size: ' . strlen($content));

$s = CSSJanus::transform($content);
var_dump('transformed size: ' . strlen($s));
```
Output with 1.2.0:
```
string(17) "read size: 366184"
string(19) "transformed size: 0"
```
The transformation yields an empty string without emitting any warnings.

Output with this PR:
```
string(17) "read size: 366184"
string(24) "transformed size: 366410"
```
(Tested on a Mac, php versions 5.6.30, 7.0.20 and 7.1.6)

The exact origin of the problem is unknown to me. Some details can be found on this issue: https://github.com/cssjanus/php-cssjanus/issues/14, but as it happens the workaround that I posted there doesn't work for all failing files, and some files like this one fail on PHP 5.6 too (but with `PREG_BACKTRACK_LIMIT_ERROR` instead).

I hope this PR can be merged soon.

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/cssjanus/php-cssjanus/pull/19. Please report to https://github.com/cssjanus/php-cssjanus/issues/14 or create a new issue if problems on PHP 7 persist after the next release.

**Pull request closed without merging**
