### PR TITLE
tests: Bump target compatibility to 1.3.1

### PR DESCRIPTION
**Pull request by jdforrester**
For #20 when this actually works.

### CODE REVIEW

**Comment by reedy** [comment]
https://github.com/cssjanus/cssjanus/compare/v1.2.1...v1.3.1

**Comment by reedy** [comment]
The fix for https://github.com/cssjanus/cssjanus/commit/d0d6a1ce0c65b1760236e5e91d932097293ffa2b is in https://github.com/cssjanus/php-cssjanus/pull/19

Probably only https://github.com/cssjanus/cssjanus/commit/f5b34a130bfa4c4a5abb844a9c95ae88f0c3d262 that needs porting over still?

**Comment by jdforrester** [comment]
No, if I drop down to 1.3.0 it fails with:

```

There was 1 failure:

1) CSSJanusTest::testTransform with data set #278 ('a.padding-left .\31 { color: red; }', array(false, false), 'a.padding-left .\31 { color: red; }', 'leave class names alone')
leave class names alone
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'a.padding-left .\31 { color: red; }'
+'a.padding-right .\31 { color: red; }'

/Users/jdforrester/Documents/code/php-cssjanus/test/suites/CSSJanusTest.php:55
```

**Comment by reedy** [comment]
That's https://github.com/cssjanus/cssjanus/commit/d0d6a1ce0c65b1760236e5e91d932097293ffa2b (where the test comes from). The extra escaping is in https://github.com/cssjanus/php-cssjanus/pull/19

I wonder if we should pull the escaping changes out of that commit, and push them separately

**Comment by jdforrester** [comment]
Pushed into #19 .

**Pull request closed without merging**
